export const APPLICANT_STATUS = {
  PENDING: 'APPLICANT_STATUS.PENDING',
  SCHEDULED_INTERVIEW: 'APPLICANT_STATUS.SCHEDULED_INTERVIEW',
  NOT_ENOUGH_INTERVIEWS: 'APPLICANT_STATUS.NOT_ENOUGH_INTERVIEWS',
  FAILED_INTERVIEW: 'APPLICANT_STATUS.FAILED_INTERVIEW',
  PASSED_INTERVIEW: 'APPLICANT_STATUS.PASSED_INTERVIEW',
  SENT_REJECTED_AT_INTERVIEW_NOTIFICATION: 'APPLICANT_STATUS.SENT_REJECTED_AT_INTERVIEW_NOTIFICATION',

  NOT_ENOUGH_LOGIC_EVALUATIONS: 'APPLICANT_STATUS.NOT_ENOUGH_LOGIC_EVALUATIONS',
  FAILED_LOGIC_EVALUATION: 'APPLICANT_STATUS.FAILED_LOGIC_EVALUATION',
  PASSED_LOGIC_EVALUATION: 'APPLICANT_STATUS.PASSED_LOGIC_EVALUATION',
  SENT_REJECTED_AT_LOGIC_EVALUATION_NOTIFICATION: 'APPLICANT_STATUS.SENT_REJECTED_AT_LOGIC_EVALUATION_NOTIFICATION',

  SENT_INVITATION: 'APPLICANT_STATUS.SENT_INVITATION',
  DECLINED_INVITATION: 'APPLICANT_STATUS.DECLINED_INVITATION',
  ACCEPTED_INVITATION: 'APPLICANT_STATUS.ACCEPTED_INVITATION',
}

export const LOADING_STATUS = {
  FAILURE: 'LOADING_STATUS.FAILURE',
  PENDING: 'LOADING_STATUS.PENDING',
  REQUEST: 'LOADING_STATUS.REQUEST',
  SUCCESS: 'LOADING_STATUS.SUCCESS',
}

export const FORM_CONTROL_STATUS = {
  FAILURE: 'FORM_CONTROL_STATUS.FAILURE',
  PENDING: 'FORM_CONTROL_STATUS.PENDING',
  REQUEST: 'FORM_CONTROL_STATUS.REQUEST',
  SUCCESS: 'FORM_CONTROL_STATUS.SUCCESS',
  SUBMITTED: 'FORM_CONTROL_STATUS.SUBMITTED',
  INDETERMINATE: 'FORM_CONTROL_STATUS.INDETERMINATE',
}
